#!/usr/local/bin/python3

import sys
import os


if len(sys.argv) > 2:
    print('Usage: deftnw <folder_name>')
    sys.exit()
elif len(sys.argv) == 1:
    os.system('/usr/local/bin/emacs -nw -q --load "~/.deft"')
    sys.exit()



# duplicate .deft to temp and change folder
cfg = open(os.path.expanduser('~/.deft')).readlines()


for i, c in enumerate(cfg):
    if c.startswith('(setq deft-directory'):
        cfg[i] = f'(setq deft-directory "{os.path.join(os.getcwd(), sys.argv[1])}")\n'

open(os.path.expanduser('~/bin/.deft_tmp'), 'w').write(''.join(cfg))
os.system('/usr/local/bin/emacs -nw -q --load "~/bin/.deft_tmp"')

