#!/usr/local/bin/python3

import scipy.io as sio
import sys
import os

if len(sys.argv) != 2:
    print("Usage: matvars <filename>")
    sys.exit()
else:
    data = sio.loadmat(os.getcwd() + '/' + sys.argv[1])
    keys = sorted(data.keys())
    for k in keys:
        if k[:2] != '__':
            print(k + '\t' + str(data[k].shape))
