#!/bin/bash


if [[ $1 -eq 0 ]] ; then
    echo 'Usage: time_cmd <pid>'
    exit 0
fi

pid="$1"
# record process start time to a log file
ps -o lstart= -p $pid > watch_process_$pid.log

# Check process every 2 seconds, using watch command.
# When process is running, record current time to log file.
# When process has finished, send_alert.sh will be executed.
while ps -o lstart= -p $pid; do
    date | tee -a watch_process_$pid.log
    sleep 5
done
